#Deriving the base image
FROM python:3.12

# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /fx/OPCUA-Server

# Install requirements
COPY ./req.txt  /requirements/req.txt
RUN pip install --no-cache-dir --upgrade -r /requirements/req.txt


#CMD instruction should be used to run the software
#contained by your image, along with any arguments.
CMD [ "python",  "-u", "./app.py"]
