services:
  Data-Source:
    image: data-source-image
    container_name: MX-Adapter-Data-Source
    restart: always
    ports:
      - 8222:8000
    networks:
      - MX-Adapter-network
    volumes: 
      - MX-Adapter-volume:/fx

  OPCUA-Server:
    image: opcua-server-image
    container_name: MX-Adapter-OPCUA-Server
    restart: always
    ports:
      - 4840:4840
    networks:
      - MX-Adapter-network
    volumes: 
      - MX-Adapter-volume:/fx

networks:
  MX-Adapter-network:

volumes:
  MX-Adapter-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /daten/docker-projects/Factory_X_Trumpf_demonstrator/fx-ccm-dataspace-poc-business-int-logic
